# change tabs 
[[mgr.prepend_keymap]]
on = "H"
run = "tab_switch -1 --relative"
desc = "Switch to previous tab"

[[mgr.prepend_keymap]]
on = "L"
run = "tab_switch 1 --relative"
desc = "Switch to next tab"
# relative-motions plugin
[[mgr.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

# chmod plguin
[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

# recycle bin plugin
[[mgr.prepend_keymap]]
on = ["g", "t"]
run = "plugin recycle-bin open"
desc = "Go to Trash"

[[mgr.prepend_keymap]]
on = ["T", "o"]
run = "plugin recycle-bin open"
desc = "Open Trash"

[[mgr.prepend_keymap]]
on = ["T", "e"]
run = "plugin recycle-bin empty"
desc = "Empty Trash"

[[mgr.prepend_keymap]]
on = ["T", "d"]
run = "plugin recycle-bin delete"
desc = "Delete from Trash"

[[mgr.prepend_keymap]]
on = ["T", "D"]
run = "plugin recycle-bin emptyDays"
desc = "Empty by days deleted"

[[mgr.prepend_keymap]]
on = ["T", "r"]
run = "plugin recycle-bin restore"
desc = "Restore from Trash"

# drag and drop via dragon-drop
[[mgr.prepend_keymap]]
on = "<C-n>"
run = 'shell -- dragon-drop -x -i -T "$1"'

# mount.yazi
[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

# copy to wl-clipboard
[[mgr.prepend_keymap]]
on = "Y"
run = ["plugin wl-clipboard"]
